embedding:
  provider: "openai"
  model_id: "text-embedding-ada-002"
  api_key: "YOUR_OPENAI_KEY"

llm:
  provider: "openai"
  model_id: "gpt-3.5-turbo"
  api_key: "YOUR_OPENAI_KEY"

vector_db:
  provider: "qdrant"
  host: "http://localhost:6333"
  collection: "documents"

sql:
  connection_string: "mysql+pymysql://user:password@localhost:3306/mydb"

history:
  db_uri: "sqlite:///chat_history.db"
